packages:
  - blocklets/*
  - packages/*
  - framework/*

onlyBuiltDependencies:
  - '@blocklet/puppeteer'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - canvas
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - faiss-node
  - fast-folder-size
  - keccak
  - leveldown
  - nx
  - onnxruntime-node
  - protobufjs
  - secp256k1
  - sharp
  - simple-git-hooks
  - sqlite3
  - tree-sitter
  - unrs-resolver

overrides:
  '@abtnode/client': '^1.16.48'
  '@abtnode/constant': '^1.16.50'
  '@abtnode/cron': '^1.16.50'
  '@abtnode/file-stream-rotator': '^0.6.3'
  '@arcblock/did': '^1.24.7'
  '@arcblock/did-connect': '@arcblock/did-connect-react@^3.1.5'
  '@arcblock/did-connect-js': '^1.24.7'
  '@arcblock/did-connect-react': '^3.1.33'
  '@arcblock/did-ext': '^1.24.7'
  '@arcblock/did-util': '^1.24.7'
  '@arcblock/jwt': '^1.24.7'
  '@arcblock/ux': '^3.1.33'
  '@arcblock/ws': '^1.24.7'
  '@blocklet/ai-runtime': 'workspace:^'
  '@blocklet/constant': '^1.16.50'
  '@blocklet/discuss-kit': '^2.4.64'
  '@blocklet/discuss-kit-ux': '^2.4.64'
  '@blocklet/editor': '^2.4.64'
  '@blocklet/js-sdk': '^1.16.50'
  '@blocklet/logger': '^1.16.50'
  '@blocklet/meta': '^1.16.50'
  '@blocklet/sdk': '^1.16.50'
  '@blocklet/ui-react': '^3.1.33'
  '@blocklet/uploader': '^0.2.7'
  '@emotion/cache': '^11.14.0'
  '@emotion/css': '^11.13.5'
  '@emotion/react': '^11.14.0'
  '@mui/base': '^5.0.0-beta.40'
  '@mui/icons-material': '^7.2.0'
  '@mui/lab': '^7.0.0-beta.14'
  '@mui/material': '^7.2.0'
  '@nedb/core': '^2.1.5'
  '@ocap/asset': '^1.24.7'
  '@ocap/mcrypto': '^1.24.7'
  '@ocap/proto': '^1.24.7'
  '@ocap/types': '^1.24.7'
  '@ocap/util': '^1.24.7'
  '@ocap/wallet': '^1.24.7'
  '@types/react': '^19.1.8'
  '@types/react-dom': '^19.1.6'
  'axios': '^1.7.5'
  'gpt-tokens': '1.2.0'
  'isomorphic-git': '1.27.1'
  'json-stable-stringify': '1.3.0'
  'monaco-editor': '0.50.0'
  'openapi3-ts': '4.3.1'
  'queue': '6.0.2'
  'react-dnd': '^16.0.1'
  'react-dnd-html5-backend': '^16.0.1'
  'umzug': '^3.8.1'
  'vite-tsconfig-paths': '5.1.4'
  'ws': '^8.18.0'
