import { expect, test } from '@playwright/test';

import { createProject } from './utils/project';

test.beforeEach('route to agent page', async ({ page }) => {
  await createProject({ page });
});

test('agent name and description', async ({ page }) => {
  const title = page.getByTestId('agent-name').locator('input');
  await title.click();
  await title.fill('E2E Test');
  await title.press('Enter');
  console.log('title', title, title.getAttribute('value'));
  expect(await title.getAttribute('value')).toBe('E2E Test');

  const description = page.getByTestId('agent-description').locator('textarea').first();
  await description.click();
  await description.fill('this is generated by e2e');
  await title.press('Enter');
  await expect(page.getByTestId('agent-description')).toContainText('this is generated by e2e');
});

test('add/delete/edit input', async ({ page }) => {
  const inputTable = page.getByTestId('input-settings');
  const rows = page.getByTestId('input-table').locator('.input-table-row');
  const count = await rows.count();
  await inputTable.getByRole('button', { name: 'Input', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Custom input' }).click();
  expect(await rows.count()).toBe(count + 1);

  const newLine = rows.last();
  const nameCol = newLine.getByPlaceholder('Name of Input');
  await nameCol.click();
  await nameCol.fill('e2eTest');
  await expect(nameCol).toHaveValue('e2eTest');

  let length = await rows.count();
  while (length > 0) {
    const line = rows.first();
    await line.locator('td').last().getByRole('button').last().click();
    await page.getByRole('menuitem', { name: 'Delete' }).click();
    length = await rows.count();
    console.log('length', length);
  }
  expect(await rows.count()).toBe(0);
});

test('another agent', async ({ page }) => {
  const rows = page.getByTestId('input-table').locator('.input-table-row');
  const newLine = rows.last();
  await newLine.locator('td').nth(1).click();

  await page.getByRole('menuitem', { name: 'Another Agent' }).click();
  // todo: 这里未设置输入的 agent
  await page.getByRole('button', { name: 'Ok' }).click();
  await expect(newLine).toContainText('Agent Outputs');
});

test('memory', async ({ page }) => {
  await page.getByTestId('project-page-variables').click();
  await page.waitForSelector('[data-testid=variable-list]', { state: 'visible' });
  // 判断是否已经存在 memory
  let addMemory = page.getByTestId('variable-list').getByRole('button', { name: 'Memory' });
  if (!addMemory) {
    addMemory = page.getByTestId('add-new-memory');
  }
  await addMemory.click();
  await page.locator('input[name="key"]').fill('e2eTest');
  await page.locator('input[name="defaultValue"]').fill('e2eTest');

  if (await page.getByText('Data already exist.').isVisible()) {
    await page.getByRole('button', { name: 'Cancel' }).click();
  } else {
    await page.getByRole('button', { name: 'Save' }).click();
  }
  await expect(page.getByTestId('variable-list').getByText('e2eTest')).toBeVisible();

  await page.getByTestId('project-page-prompts').click();
  await page.getByLabel('New Agent').getByRole('button').click({ force: true });
  const rows = page.getByTestId('input-table').locator('.input-table-row');
  const newLine = rows.last();
  await newLine.locator('td').nth(1).click();

  // todo: do more actions
  await page.getByRole('menu').getByText('Memory').click();
  await page.getByPlaceholder('Select a memory').click();
  await page.getByRole('option', { name: 'e2eTest' }).first().click();
  await page.getByRole('button', { name: 'Ok' }).click();

  await expect(newLine).toContainText('Memory');
});

test('create knowledge', async ({ page }) => {
  await page.getByTestId('project-page-knowledge').click();
  await page.getByText('Add Knowledge').click();
  await page.getByPlaceholder('Give your knowledge a name (e').fill('e2eTest');
  await page.locator('textarea[name="description"]').fill('e2eTest');

  const responsePromise = page.waitForResponse(/\/api\/datasets/);
  await page.getByRole('button', { name: 'Create' }).click();
  await responsePromise;

  await page.getByTestId('project-page-prompts').click();
  await page.getByLabel('New Agent').getByRole('button').click({ force: true });
  const rows = page.getByTestId('input-table').locator('.input-table-row');
  const newLine = rows.last();
  await newLine.locator('td').nth(1).click();

  await page.getByRole('menu').getByText('Knowledge').click();
  await page.getByPlaceholder('Select a knowledge to query').click();
  await page.getByRole('option', { name: 'e2eTest' }).first().click();
  await page.getByRole('button', { name: 'Ok' }).click();

  await expect(rows.first()).toContainText('Knowledge');
});

test('set model', async ({ page }) => {
  await page.getByTestId('OpenAIIcon').locator('rect').click();
  await page.waitForSelector('[data-testid=prompt-setting-model]');

  const model = page.getByTestId('prompt-setting-model');
  await model.click();
  await page.getByRole('option', { name: 'GPT4', exact: true }).click();

  const temperature = page.getByTestId('prompt-setting-temperature');
  await temperature.getByRole('textbox').fill('2');

  const topP = page.getByTestId('prompt-setting-topP');
  await topP.getByRole('textbox').fill('0');

  const frequencyPenalty = page.getByTestId('prompt-setting-frequencyPenalty');
  await frequencyPenalty.getByRole('textbox').fill('2');

  const presencePenalty = page.getByTestId('prompt-setting-presencePenalty');
  await presencePenalty.getByRole('textbox').fill('2');

  const maxTokens = page.getByTestId('prompt-setting-maxTokens');
  await maxTokens.getByRole('textbox').fill('128000');
  await page.waitForSelector('[data-testid=prompt-setting-maxTokens]');

  await expect(model).toHaveText('GPT4');
  await expect(temperature.getByRole('textbox')).toHaveValue('2');
  await expect(topP.getByRole('textbox')).toHaveValue('0');
  await expect(frequencyPenalty.getByRole('textbox')).toHaveValue('2');
  await expect(presencePenalty.getByRole('textbox')).toHaveValue('2');
  await expect(maxTokens.getByRole('textbox')).toHaveValue('128000');
});

test('prompt message', async ({ page }) => {
  const prompts = page.locator('.prompt-item');
  await page.getByRole('button', { name: 'Prompt Message' }).click();
  expect(await prompts.count()).toBe(2);

  await prompts.last().getByRole('textbox').fill('e2e test');
  await expect(prompts.last().locator(':text("e2e test")')).toBeVisible();
});

test('agent output', async ({ page }) => {
  await page.getByTestId('add-output-variable-button').click();
  await page.getByTestId('add-output-variable-button-custom-output').click();

  const customOutputLine = page.locator('.output-variable-row').last();
  const nameCell = customOutputLine.getByPlaceholder('Output name');
  await nameCell.fill('customOutput');

  const descriptionCell = customOutputLine.getByPlaceholder('Prompt to LLM how to fill');
  await descriptionCell.fill('this is e2e test');

  const formatCell = customOutputLine.locator('td').nth(2);
  await formatCell.click();
  await page.getByRole('option', { name: 'Text' }).click();

  const requiredCell = customOutputLine.getByRole('checkbox');
  await requiredCell.check();

  await customOutputLine.locator('td').last().getByRole('button').click();
  await page.getByTestId('output-actions-cell-setting').click();
  const dialog = await page.getByTestId('output-actions-cell-dialog');
  await dialog.getByPlaceholder('The title displayed above').fill('e2eTest');
  await dialog.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Markdown View' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();

  const appearanceCell = customOutputLine.locator('td').nth(4);

  await expect(nameCell).toHaveValue('customOutput');
  await expect(descriptionCell).toHaveValue('this is e2e test');
  await expect(formatCell).toHaveText('Text');
  await expect(requiredCell).toBeChecked();
  await expect(appearanceCell).toContainText('Markdown View');
});

test('agent debug', async ({ page }) => {
  const input = page.locator("[data-testid='debug-mode-parameter'] textarea").first();
  await input.fill('hello');

  const list = page.locator("[data-testid='virtuoso-item-list']>div");
  const count = await list.count();
  const responsePromise = page.waitForResponse(
    (response) => response.url().includes('/ai/call') && response.status() === 200
  );
  await page.getByRole('button', { name: 'Execute' }).click();
  await responsePromise;
  const newCount = await list.count();

  expect(newCount).toBe(count + 2);
  await expect(list.last()).toContainText('AI Chat');

  // clear session
  await page.getByLabel('Clear current session history').click();
  expect(await page.locator("[data-testid='virtuoso-item-list']>div").count()).toBe(0);

  // new session
  await page.getByTestId('session-select').click();
  await page.getByRole('option', { name: 'New Session' }).click();

  // delete session
  await page.getByTestId('session-delete-button').click({ force: true });

  await page.getByTestId('session-select').click();
  expect(await page.getByTestId('session-select-item').count()).toBe(1);
});

test('debug tests', async ({ page }) => {
  const input = page.locator("[data-testid='debug-mode-parameter'] textarea").first();
  await input.fill('hello');
  await page.getByRole('button', { name: 'Save as test case' }).click();

  const firstCase = page.locator('test-case').first();
  const responsePromise = page.waitForResponse(/\/ai\/call/);
  await firstCase.getByTestId('run-test').first().click();
  await responsePromise;
});

test('collaboration', async ({ page }) => {
  await page.getByTestId('debug-view-collaboration').click();
  await page.locator('.be-editable.notranslate').fill('this is e2e test');
  const responsePromise = page.waitForResponse(/\/api\/comments/);
  await page.getByRole('button', { name: 'Comment' }).click();
  await responsePromise;

  expect(await page.locator('.comment-list').locator('>div').count()).toBe(1);
});
