id: BLOCK_CHAIN_ASSISTANT_PROJECT_ID
name: Block Chain Bot
description: A simple block chain assistant project
createdAt: '2021-01-01T00:00:00Z'
updatedAt: '2021-01-01T00:00:00Z'
createdBy: xxxxxxxxxxxxxxxxxxxxxx
