id: block-chain-assistant
name: Block Chain Assistant
description: A simple block chain assistant project
createdAt: '2021-01-01T00:00:00Z'
updatedAt: '2021-01-01T00:00:00Z'
createdBy: xxxxxxxxxxxxxxxxxxxxxx
