import {
  Bg,
  Ch,
  Cz,
  De,
  Dk,
  Es,
  Fi,
  Fr,
  Gr,
  Hu,
  Id,
  Il,
  In,
  It,
  Jp,
  Kr,
  Nl,
  No,
  Pl,
  Pt,
  Ro,
  Ru,
  Sa,
  Se,
  Sk,
  Th,
  Tr,
  Tw,
  Us,
  Vn,
} from 'react-flags-select';

export const languages = [
  { en: 'English', ch: 'English', abbr: 'US', flag: Us, cn: '英语' },
  { en: 'Simplified Chinese', ch: '简体中文', abbr: 'CH', flag: Ch, cn: '简体中文' },
  { en: 'Traditional Chinese', ch: '繁体中文', abbr: 'ZH-TW', flag: Tw, cn: '繁体中文' },
  { en: 'Spanish', ch: 'Español', abbr: 'ES', flag: Es, cn: '西班牙语' },
  { en: 'French', ch: 'Français', abbr: 'FR', flag: Fr, cn: '法语' },
  { en: 'German', ch: 'Deutsch', abbr: 'DE', flag: De, cn: '德语' },
  { en: 'Italian', ch: 'Italiano', abbr: 'IT', flag: It, cn: '意大利语' },
  { en: 'Portuguese', ch: 'Português', abbr: 'PT', flag: Pt, cn: '葡萄牙语' },
  { en: 'Japanese', ch: '日本語', abbr: 'JP', flag: Jp, cn: '日语' },
  { en: 'Korean', ch: '한국어', abbr: 'KR', flag: Kr, cn: '韩语' },
  { en: 'Russian', ch: 'Русский', abbr: 'RU', flag: Ru, cn: '俄语' },
  { en: 'Polish', ch: 'Polski', abbr: 'PL', flag: Pl, cn: '波兰语' },
  { en: 'Arabic', ch: 'العربية', abbr: 'SA', flag: Sa, cn: '阿拉伯语' },
  { en: 'Dutch', ch: 'Nederlands', abbr: 'NL', flag: Nl, cn: '荷兰语' },
  { en: 'Swedish', ch: 'Svenska', abbr: 'SE', flag: Se, cn: '瑞典语' },
  { en: 'Finnish', ch: 'Suomi', abbr: 'FI', flag: Fi, cn: '芬兰语' },
  { en: 'Czech', ch: 'Čeština', abbr: 'CZ', flag: Cz, cn: '捷克语' },
  { en: 'Danish', ch: 'Dansk', abbr: 'DK', flag: Dk, cn: '丹麦语' },
  { en: 'Greek', ch: 'Ελληνικά', abbr: 'GR', flag: Gr, cn: '希腊语' },
  { en: 'Romanian', ch: 'Română', abbr: 'RO', flag: Ro, cn: '罗马尼亚语' },
  { en: 'Hungarian', ch: 'Magyar', abbr: 'HU', flag: Hu, cn: '匈牙利语' },
  { en: 'Bulgarian', ch: 'Български', abbr: 'BG', flag: Bg, cn: '保加利亚语' },
  { en: 'Slovak', ch: 'Slovenčina', abbr: 'SK', flag: Sk, cn: '斯洛伐克语' },
  { en: 'Norwegian', ch: 'Norsk', abbr: 'NO', flag: No, cn: '挪威语' },
  { en: 'Hebrew', ch: 'עברית', abbr: 'IL', flag: Il, cn: '希伯来语' },
  { en: 'Turkish', ch: 'Türkçe', abbr: 'TR', flag: Tr, cn: '土耳其语' },
  { en: 'Thai', ch: 'ไทย', abbr: 'TH', flag: Th, cn: '泰语' },
  { en: 'Indonesian', ch: 'Bahasa Indonesia', abbr: 'ID', flag: Id, cn: '印尼语' },
  { en: 'Vietnamese', ch: 'Tiếng Việt', abbr: 'VN', flag: Vn, cn: '越南语' },
  { en: 'Hindi', ch: 'हिन्दी', abbr: 'IN', flag: In, cn: '印地语' },
];
