import {
  Bg,
  Ch,
  Cz,
  De,
  Dk,
  Es,
  Fi,
  Fr,
  Gr,
  Hu,
  Id,
  Il,
  In,
  It,
  Jp,
  Kr,
  Nl,
  No,
  Pl,
  Pt,
  Ro,
  Ru,
  Sa,
  Se,
  Sk,
  Th,
  Tr,
  Tw,
  Us,
  Vn,
} from 'react-flags-select';

export const languages = [
  { en: 'English', ch: 'English', abbr: 'US', flag: Us },
  { en: 'Simplified Chinese', ch: '简体中文', abbr: 'CH', flag: Ch },
  { en: 'Traditional Chinese', ch: '繁体中文', abbr: 'TW', flag: Tw },
  { en: 'Spanish', ch: 'Español', abbr: 'ES', flag: Es },
  { en: 'French', ch: 'Français', abbr: 'FR', flag: Fr },
  { en: 'German', ch: 'Deutsch', abbr: 'DE', flag: De },
  { en: 'Italian', ch: 'Italiano', abbr: 'IT', flag: It },
  { en: 'Portuguese', ch: 'Português', abbr: 'PT', flag: Pt },
  { en: 'Japanese', ch: '日本語', abbr: 'JP', flag: Jp },
  { en: 'Korean', ch: '한국어', abbr: 'KR', flag: Kr },
  { en: 'Russian', ch: 'Русский', abbr: 'RU', flag: Ru },
  { en: 'Polish', ch: 'Polski', abbr: 'PL', flag: Pl },
  { en: 'Arabic', ch: 'العربية', abbr: 'SA', flag: Sa },
  { en: 'Dutch', ch: 'Nederlands', abbr: 'NL', flag: Nl },
  { en: 'Swedish', ch: 'Svenska', abbr: 'SE', flag: Se },
  { en: 'Finnish', ch: 'Suomi', abbr: 'FI', flag: Fi },
  { en: 'Czech', ch: 'Čeština', abbr: 'CZ', flag: Cz },
  { en: 'Danish', ch: 'Dansk', abbr: 'DK', flag: Dk },
  { en: 'Greek', ch: 'Ελληνικά', abbr: 'GR', flag: Gr },
  { en: 'Romanian', ch: 'Română', abbr: 'RO', flag: Ro },
  { en: 'Hungarian', ch: 'Magyar', abbr: 'HU', flag: Hu },
  { en: 'Bulgarian', ch: 'Български', abbr: 'BG', flag: Bg },
  { en: 'Slovak', ch: 'Slovenčina', abbr: 'SK', flag: Sk },
  { en: 'Norwegian', ch: 'Norsk', abbr: 'NO', flag: No },
  { en: 'Hebrew', ch: 'עברית', abbr: 'IL', flag: Il },
  { en: 'Turkish', ch: 'Türkçe', abbr: 'TR', flag: Tr },
  { en: 'Thai', ch: 'ไทย', abbr: 'TH', flag: Th },
  { en: 'Indonesian', ch: 'Bahasa Indonesia', abbr: 'ID', flag: Id },
  { en: 'Vietnamese', ch: 'Tiếng Việt', abbr: 'VN', flag: Vn },
  { en: 'Hindi', ch: 'हिन्दी', abbr: 'IN', flag: In },
];
