paths:
  /api/messages:
    get:
      summary: Get history messages
      x-summary-zh: 获取历史信息
      description: Retrieve messages based on sessionId, last N messages, or keyword
      x-description-zh: 根据 sessionId、最后N条消息或关键字检索历史消息
      tags:
        - Sessions
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of last messages to retrieve
          x-description-zh: 检索的消息的数目
        - in: query
          name: keyword
          schema:
            type: string
          description: Keyword to search in messages
          x-description-zh: 在消息中搜索的关键字
      responses:
        '200':
          description: A list of history messages
          x-description-zh: 检索历史消息列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        taskId:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
  /api/ai/todo:
    get:
      summary: 未命名接口
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: string
                required:
                  - name
                  - age
