export async function getSupportedModels() {
  return [
    {
      brand: 'OpenAI',
      model: 'gpt-3.5-turbo',
      temperatureMin: 0,
      temperatureMax: 2,
      temperatureDefault: 1,
      topPMin: 0,
      topPMax: 1,
      topPDefault: 1,
      presencePenaltyMin: -2,
      presencePenaltyMax: 2,
      presencePenaltyDefault: 0,
      frequencyPenaltyMin: -2,
      frequencyPenaltyMax: 2,
      frequencyPenaltyDefault: 0,
      maxTokensMin: 1,
      maxTokensMax: 4096,
      maxTokensDefault: 4096,
    },
    {
      brand: 'OpenAI',
      model: 'gpt-3.5-turbo-16k',
      temperatureMin: 0,
      temperatureMax: 2,
      temperatureDefault: 1,
      topPMin: 0,
      topPMax: 1,
      topPDefault: 1,
      presencePenaltyMin: -2,
      presencePenaltyMax: 2,
      presencePenaltyDefault: 0,
      frequencyPenaltyMin: -2,
      frequencyPenaltyMax: 2,
      frequencyPenaltyDefault: 0,
      maxTokensMin: 1,
      maxTokensMax: 16385,
      maxTokensDefault: 16385,
    },
    {
      brand: 'OpenAI',
      model: 'gpt-3.5-turbo-0613',
      temperatureMin: 0,
      temperatureMax: 2,
      temperatureDefault: 1,
      topPMin: 0,
      topPMax: 1,
      topPDefault: 1,
      presencePenaltyMin: -2,
      presencePenaltyMax: 2,
      presencePenaltyDefault: 0,
      frequencyPenaltyMin: -2,
      frequencyPenaltyMax: 2,
      frequencyPenaltyDefault: 0,
      maxTokensMin: 1,
      maxTokensMax: 4096,
      maxTokensDefault: 4096,
    },
    {
      brand: 'OpenAI',
      model: 'gpt-3.5-turbo-16k-0613',
      temperatureMin: 0,
      temperatureMax: 2,
      temperatureDefault: 1,
      topPMin: 0,
      topPMax: 1,
      topPDefault: 1,
      presencePenaltyMin: -2,
      presencePenaltyMax: 2,
      presencePenaltyDefault: 0,
      frequencyPenaltyMin: -2,
      frequencyPenaltyMax: 2,
      frequencyPenaltyDefault: 0,
      maxTokensMin: 1,
      maxTokensMax: 16385,
      maxTokensDefault: 16385,
    },
    {
      brand: 'Hugging Face',
      model: 'Hugging Face',
      disabled: true,
    },
    {
      brand: 'Azure OpenAI',
      model: 'Azure OpenAI',
      disabled: true,
    },
    {
      brand: 'Replicate',
      model: 'Replicate',
      disabled: true,
    },
    {
      brand: 'Vertex AI',
      model: 'Vertex AI',
      disabled: true,
    },
  ];
}
