name: CI

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

on:
  pull_request:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build libs
        run: pnpm build:libs

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
