name: Deploy

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  push:
    branches:
      - main

jobs:
  version-check:
    name: Check version by local workflow
    uses: ./.github/workflows/version-check.yml

  deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    needs: version-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.version-check.outputs.folders) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build libs
        run: pnpm build:libs

      - name: Publish to NPM
        if: "contains(matrix.dir , 'packages/') || contains(matrix.dir , 'framework/')"
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          cd ${{ matrix.dir }}
          pnpm publish --access public --no-git-checks

      - name: Blocklet workflow
        if: "contains(matrix.dir , 'blocklets/')"
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_TEST }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: false
          skip-readme: true
          skip-release: true
          working-directory: ${{ matrix.dir }}
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          deploy-app-did: zNKq56yExCXmaQpir9nFRu9aPFSYvSoKQr1e
