name: Deploy

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build libs
        run: pnpm build:libs

      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          VERSION=$(cat version | awk '{$1=$1;print}')
          echo "publish version ${VERSION}"
          pnpm publish --filter "@blocklet/*" --access public --no-git-checks

      - name: Blocklet workflow
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_TEST }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: false
          working-directory: blocklets/ai-studio
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          deploy-app-did: zNKq56yExCXmaQpir9nFRu9aPFSYvSoKQr1e
          deploy-mount-point: /
