name: upload-to-production-store

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  push:
    branches:
      - release

jobs:
  version-check:
    name: Check version by local workflow
    uses: ./.github/workflows/version-check.yml

  deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    needs: version-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.version-check.outputs.folders) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: release

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build libs
        run: pnpm build:libs

      - name: Upload to production store
        if: "contains(matrix.dir , 'blocklets/')"
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_PROD }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-release: true
          skip-upload: false
          skip-deploy: true
          working-directory: ${{ matrix.dir }}
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_PROD }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_PROD }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
